# Generated by Django 6.0.1 on 2026-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voting_voting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='num_choices',
            field=models.PositiveIntegerField(default=2, help_text='Количество вариантов голоса'),
        ),
    ]
