# Generated by Django 6.0.1 on 2026-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voting_num_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='max_votes',
            field=models.PositiveIntegerField(default=1, help_text='Максимум голосов от одного пользователя'),
        ),
    ]
