# Generated by Django 6.0.1 on 2026-01-10 14:32

import django.db.models.deletion
import voting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_max_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимное голосование'),
        ),
        migrations.AddField(
            model_name='voting',
            name='end_at',
            field=models.DateTimeField(default=voting.models.get_end_time, help_text='Время по МСК'),
        ),
        migrations.AlterField(
            model_name='report',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Жалобы', to='voting.voting'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='max_votes',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимум голосов от одного пользователя'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='num_choices',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество вариантов голоса'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
    ]
