# Generated by Django 6.0.1 on 2026-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_anonymous_voting_end_at_alter_report_voting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='commentaries',
            field=models.BooleanField(default=True, verbose_name='Коментарии'),
        ),
    ]
