# Generated by Django 6.0.1 on 2026-01-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voting_commentaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
