# Generated by Django 6.0.1 on 2026-01-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_rename_description_report_text_remove_report_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(choices=[('rights', 'Нарушены авторские права'), ('fake', 'Ложная информация'), ('unpleasant', 'Неприятный контент'), ('offended', 'Это меня оскорбило'), ('other', 'Другое')], default='rights', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reports', to='voting.voting'),
        ),
    ]
