# Generated by Django 6.0 on 2026-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_remove_report_text_report_description_report_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='active'),
        ),
    ]
