# Generated by Django 6.0 on 2026-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='active',
            field=models.CharField(default=True),
        ),
    ]
