# Generated by Django 6.0 on 2026-01-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_report_status_report_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
