# Generated by Django 6.0 on 2026-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_voting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
