# Generated by Django 6.0 on 2026-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_voting_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
