# Generated by Django 6.0 on 2026-01-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='user', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
