# Generated by Django 6.0 on 2026-01-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_profile_user_nickname_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_nickname',
            new_name='user',
        ),
    ]
