# Generated by Django 6.0.1 on 2026-01-09 11:27

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_nickname_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default=user.models.get_random_avatars, upload_to='avatars/'),
        ),
    ]
